# to create an artefacts folder
artifacts_root: artifacts

# you can make changes here if you want to change directory name
data_ingestion:
  root_dir: artifacts/data_ingestion  
  # data url
  source_URL: https://github.com/Amitgm/text-summarizer/raw/refs/heads/main/samsumdata.zip
  # download the data inside data_ingestion folder
  local_data_file: artifacts/data_ingestion/data.zip
  # unzip the data inside data_ingestion folder
  unzip_dir: artifacts/data_ingestion
